apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-consumer
  namespace: rabbitmq-demo
type: Opaque
data:
  RABBIT_USERNAME: Z3Vlc3Q=
  RABBIT_PASSWORD: Z3Vlc3Q=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
  namespace: rabbitmq-demo
  labels:
    app: rabbitmq-consumer
spec:
  selector:
    matchLabels:
      app: rabbitmq-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
        - name: rabbitmq-consumer
          image: siakag/rabbitmq-consumer:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: RABBIT_HOST
              value: "rabbitmq-0.rabbitmq.rabbitmq-demo.svc.cluster.local"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-consumer
                  key: RABBIT_USERNAME
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-consumer
                  key: RABBIT_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-consumer
  namespace: rabbitmq-demo
  labels:
    app: rabbitmq-consumer
spec:
  type: NodePort
  selector:
    app: rabbitmq-consumer
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
